name: 2dgs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9  # Use Python 3.10 to avoid conflicts with pillow and zlib
  - pip=25.1.1
  - ffmpeg=4.2.2
  - pillow=10.2.0
  - typing_extensions=4.13.2
  - libxcb=1.15
  - pip:
      - torch==2.7.0+cu128
      - torchvision==0.22.0+cu128
      - torchaudio==2.7.0+cu128
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - open3d==0.19.0
      - mediapy==1.1.2
      - lpips==0.1.4
      - scikit-image==0.21.0
      - tqdm==4.67.1
      - trimesh==4.3.2
      - plyfile
      - opencv-python
      - numpy==1.26.4
